// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovimentosManuais.Data.Context;

namespace MovimentosManuais.Data.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MovimentosManuaisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.Movimento_Manual", b =>
                {
                    b.Property<decimal>("DAT_ANO")
                        .HasColumnType("NUMERIC(4,0)");

                    b.Property<decimal>("DAT_MES")
                        .HasColumnType("NUMERIC(2,0)");

                    b.Property<decimal>("NUM_LANCAMENTO")
                        .HasColumnType("NUMERIC(18,0)");

                    b.Property<string>("COD_PRODUTO")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("COD_COSIF")
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("COD_USUARIO")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<DateTime>("DAT_MOVIMENTO")
                        .HasColumnType("SMALLDATETIME");

                    b.Property<string>("DES_DESCRICAO")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("VAL_VALOR")
                        .HasColumnType("NUMERIC(18,2)");

                    b.HasKey("DAT_ANO", "DAT_MES", "NUM_LANCAMENTO", "COD_PRODUTO", "COD_COSIF");

                    b.HasIndex("COD_COSIF");

                    b.ToTable("MovimentosManuais");
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.Produto", b =>
                {
                    b.Property<string>("COD_PRODUTO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DES_PRODUTO")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("STA_STATUS")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.HasKey("COD_PRODUTO");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            COD_PRODUTO = "0001",
                            DES_PRODUTO = "DESC 0001",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_PRODUTO = "0002",
                            DES_PRODUTO = "DESC 0002",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_PRODUTO = "0003",
                            DES_PRODUTO = "DESC 0003",
                            STA_STATUS = "A"
                        });
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.Produto_Cosif", b =>
                {
                    b.Property<string>("COD_COSIF")
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("COD_CLASSIFICACAO")
                        .IsRequired()
                        .HasColumnType("CHAR(6)");

                    b.Property<string>("COD_PRODUTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdutoCOD_PRODUTO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("STA_STATUS")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.HasKey("COD_COSIF");

                    b.HasIndex("ProdutoCOD_PRODUTO");

                    b.ToTable("ProdutosCosifs");

                    b.HasData(
                        new
                        {
                            COD_COSIF = "48408352091",
                            COD_CLASSIFICACAO = "TESTE1",
                            COD_PRODUTO = "0001",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_COSIF = "42537728033",
                            COD_CLASSIFICACAO = "TESTE2",
                            COD_PRODUTO = "0002",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_COSIF = "07161383013",
                            COD_CLASSIFICACAO = "TESTE3",
                            COD_PRODUTO = "0003",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_COSIF = "14470492094",
                            COD_CLASSIFICACAO = "TESTE4",
                            COD_PRODUTO = "0003",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_COSIF = "25767337004",
                            COD_CLASSIFICACAO = "TESTE5",
                            COD_PRODUTO = "0002",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_COSIF = "38809386019",
                            COD_CLASSIFICACAO = "TESTE6",
                            COD_PRODUTO = "0001",
                            STA_STATUS = "A"
                        });
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.Movimento_Manual", b =>
                {
                    b.HasOne("MovimentosManuais.Domain.Entities.Produto_Cosif", null)
                        .WithMany("Contatos")
                        .HasForeignKey("COD_COSIF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Entities.Produto_Cosif", b =>
                {
                    b.HasOne("MovimentosManuais.Domain.Entities.Produto", null)
                        .WithMany("Produto_Cosifs")
                        .HasForeignKey("ProdutoCOD_PRODUTO");
                });
#pragma warning restore 612, 618
        }
    }
}
